#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - nginx
runcmd:
  - servername=$(cat /etc/hostname)
  - sed -i -e "s/to nginx/to $servername/g" /var/www/html/index.nginx-debian.html
power_state:
  mode: reboot
